FROM openjdk:8-jre

ENV MANIFOLDCF_VERSION=2.13 CIFS_VERSION=2.1.2
ENV POSTGRES_HOSTNAME=localhost POSTGRES_PORT=5432 POSTGRES_SSL=true POSTGRES_USER=manifoldcf POSTGRES_DB=manifoldcf

ADD https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh /wait-for-it.sh
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y wget ca-certificates && \
  	rm -rf /var/lib/apt/lists/*

RUN wget http://apache.mirror.rafal.ca/manifoldcf/apache-manifoldcf-${MANIFOLDCF_VERSION}/apache-manifoldcf-${MANIFOLDCF_VERSION}-bin.tar.gz && \
    tar -xzvf apache-manifoldcf-${MANIFOLDCF_VERSION}-bin.tar.gz && \
    cp -R apache-manifoldcf-${MANIFOLDCF_VERSION} /usr/share/manifoldcf && \
    chmod +x /wait-for-it.sh && \
    rm apache-manifoldcf-${MANIFOLDCF_VERSION}-bin.tar.gz

EXPOSE 8345
VOLUME /var/manifoldcf
WORKDIR /usr/share/manifoldcf/multiprocess-file-example

COPY properties.xml .
COPY entrypoint.sh /manifoldcf_entrypoint.sh

# ENTRYPOINT overrides default of `/bin/sh -c`
ENTRYPOINT ["/manifoldcf_entrypoint.sh"]
CMD ["start"]
